---
- name: install NopCommerce application
  hosts: all
  become: yes
  tasks:
    - name: update packages and install .net7
      apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present
    - name: create a directory nop
      ansible.builtin.file:
        path: nop
        mode: '0755'
        state: directory
        recurse: yes
    - name: change directory to nop
      ansible.builtin.shell: cd nop
    - name: download NopCommerce
      ansible.builtin.get_url:
        url: "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.4/nopCommerce_4.60.4_NoSource_linux_x64.zip"
        dest: "nop/nopCommerce_4.60.4_NoSource_linux_x64.zip"
    - name: install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: unzip the NopCommerce
      ansible.builtin.unarchive:
        src: nop/nopCommerce_4.60.4_NoSource_linux_x64.zip
        dest: nop/
        remote_src: yes
    - name: start the NopCommerce
      ansible.builtin.shell:
        shell: dontet Nop.Web.dll --urls "http://0.0.0.0:5000"