---
- name: install NopCommerce application
  hosts: all
  become: yes
  tasks:
    - name: update packages and install .net7
      apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present
    - name: create a directory cloud
      ansible.builtin.file:
        path: cloud
        mode: '0755'
        state: directory
        recurse: yes
    - name: change directory to cloud
      ansible.builtin.shell: cd cloud
    - name: download NopCommerce
      ansible.builtin.get_url:
        url: "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.4/nopCommerce_4.60.4_NoSource_linux_x64.zip"
        dest: "cloud/nopCommerce_4.60.4_NoSource_linux_x64.zip"
    - name: install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: unzip the NopCommerce
      ansible.builtin.unarchive:
        src: cloud/nopCommerce_4.60.4_NoSource_linux_x64.zip
        dest: cloud
        remote_src: yes
    - name: creating a folder bin
      ansible.builtin.file:
        path: 
          - cloud/bin
          - cloud/logs
        mode: '0755'
        state: directory
        recurse: yes

    - name: start the NopCommerce
      ansible.builtin.command: "cloud/dontet Nop.Web.dll --urls 'http://0.0.0.0:5000'"
      