---
- name: Install Apache Maven 3.9
  hosts: all
  become: yes  # Use sudo to gain root privileges

  tasks:
    - name: Install Java Development Kit (JDK)
      package:
        name: openjdk-11-jdk  # Use the appropriate package name for your system
        state: present
      when: ansible_distribution == 'Ubuntu'  # Adjust for your target OS

    - name: Download Apache Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /tmp/apache-maven-3.9.0-bin.tar.gz
      when: not ansible_distribution == 'Ubuntu'  # Skip this step on Ubuntu (use system package)

    - name: Extract Apache Maven
      unarchive:
        src: /tmp/apache-maven-3.9.0-bin.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/apache-maven-3.9.0  # This step will only run if the directory does not exist

    - name: Create a symbolic link to Maven
      file:
        src: /opt/apache-maven-3.9.0
        dest: /opt/maven
        state: link
